version: "3"
services:
 
 psql-db:
  image: 'postgres:14'
  container_name: psql-db
  environment:
    - PGPASSWORD=123456
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456
  ports:
    - '5434:5432'
 app:
 

   build:
     context: ./
     dockerfile: Dockerfile
   image: workshop1
   container_name: workshop_python_container
   stdin_open: true #  docker attach container_id
   tty: true
   ports:
    - "8000:8000"
   volumes:
    - .:/app
 
