version: "3"
services:
  pyhton_service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: workshop1
    container_name: workshop_python_container
    stdin_open: true #  docker attach container_id
    tty: true
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    depends_on:
     - postgres_service

  postgres_service:
    image: postgres
    container_name: workshop_postgres_container
    ports:
     - "5432:5432"
    environment:
     POSTGRES_PASSWORD: admin
    volumes:
     - .:/var/lib/postgres
